<section class="admin__page-section request-view-request-response">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Response Body') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item response-body">
            <div class="admin__page-section-item-content" style="word-wrap: break-word;" >
                <pre><code style="white-space: pre-wrap"><?php echo htmlentities($this->getRtdRequest()->getResponseBody()); ?></code></pre>
            </div>
        </div>
    </div>
</section>
